# Generated by Django 3.2.3 on 2021-05-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='session_id',
            new_name='session_key',
        ),
    ]
